organsation: OpenSAFELY 
# accounts that should not be granted general access
bots:
        - opensafely-readonly
not_studies:
        - opensafely/roadmap
        - opensafely/test-repository
        - opensafely/documentation
        - opensafely/server-instructions
        # to be deleted
        - opensafely/docker-registry
        - opensafely/repo-updater
        # to be moved
        - opensafely/matching
        - opensafely/stata-docker
