receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  file/traces:
    path: /exported/traces.json
  file/metrics:
    path: /exported/metrics.json

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/traces, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics, logging]
