name: otel-gateway tests
on: 
  pull_request:
    paths: "services/otel-gateway/**"
  workflow_dispatch:
jobs:
  test_dry_run:
    runs-on: ubuntu-latest
    name: Run CI tests
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # 3.1.0
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.8"
        install-just: true
    - name: build
      run: env -C services/otel-gateway just build
    - name: test
      run: env -C services/otel-gateway just test-ci
