name: otel-gateway tests
on: 
  pull_request:
    paths: "services/otel-gateway/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test_dry_run:
    runs-on: ubuntu-22.04
    name: Run CI tests
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: opensafely-core/setup-action@v1
      with:
        install-just: true
        install-uv: true
        cache: uv
    - name: build
      run: env -C services/otel-gateway just build
    - name: test
      run: env -C services/otel-gateway just test-ci
