name: Tests
permissions:
  contents: read
on: 
  pull_request:
  workflow_dispatch:
jobs:
  test_dry_run:
    runs-on: ubuntu-22.04
    name: Run dry-run
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: opensafely-core/setup-action@v1
      with:
        install-just: true
        install-uv: true
        cache: uv
    - name: setup environment
      run: |
        echo "ORG_TOKEN=${{ secrets.ORG_READONLY_TOKEN }}" > .env
    - name: Run dry-run
      run: |
        echo "WARNING: if this step fails randomly, you may need to update the repo secret 'ORG_READONLY_TOKEN'"
        echo "This is a Personal Access Token (Classic), that only has 'read:org'."
        echo
        echo "WARNING: ignore output from command as long as it does not fail."
        echo "It is running w/o elevated privileges needed to correctly read branch protection details"
        echo
        just manage-github --dry-run
