name: Tests
on: 
  pull_request:
  workflow_dispatch:
jobs:
  test_dry_run:
    runs-on: ubuntu-latest
    name: Run dry-run
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.8"
        cache-dependency-path: "requirements.txt"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run dry-run
      env:
        ORG_TOKEN: ${{ secrets.ORG_READONLY_TOKEN }}
      run: |
        echo "WARNING: if this step fails randomly, you may need to update the repo secret `ORG_READONLY_TOKEN`"
        echo "This is a Personal Access Token (Classic), that only has `read:org`."
        echo
        echo "WARNING: ignore output from command as long as it does not fail."
        echo "It is running w/o elevated privileges needed to correctly read branch protection details"
        echo
        python manage-github.py --dry-run
